// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ToolTrial.KiotaClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Dimensions_unit
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "in")]
        #pragma warning disable CS1591
        In,
        #pragma warning restore CS1591
        [EnumMember(Value = "cm")]
        #pragma warning disable CS1591
        Cm,
        #pragma warning restore CS1591
    }
}
