// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ToolTrial.KiotaClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Package_weightUnit
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "lb")]
        #pragma warning disable CS1591
        Lb,
        #pragma warning restore CS1591
        [EnumMember(Value = "kg")]
        #pragma warning disable CS1591
        Kg,
        #pragma warning restore CS1591
    }
}
