// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ToolTrial.KiotaClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RateResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The errors property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ToolTrial.KiotaClient.Models.ApiError>? Errors { get; set; }
#nullable restore
#else
        public List<global::ToolTrial.KiotaClient.Models.ApiError> Errors { get; set; }
#endif
        /// <summary>The rates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ToolTrial.KiotaClient.Models.Rate>? Rates { get; set; }
#nullable restore
#else
        public List<global::ToolTrial.KiotaClient.Models.Rate> Rates { get; set; }
#endif
        /// <summary>The warnings property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Warnings { get; set; }
#nullable restore
#else
        public List<string> Warnings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ToolTrial.KiotaClient.Models.RateResponse"/> and sets the default values.
        /// </summary>
        public RateResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ToolTrial.KiotaClient.Models.RateResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ToolTrial.KiotaClient.Models.RateResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ToolTrial.KiotaClient.Models.RateResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errors", n => { Errors = n.GetCollectionOfObjectValues<global::ToolTrial.KiotaClient.Models.ApiError>(global::ToolTrial.KiotaClient.Models.ApiError.CreateFromDiscriminatorValue)?.AsList(); } },
                { "rates", n => { Rates = n.GetCollectionOfObjectValues<global::ToolTrial.KiotaClient.Models.Rate>(global::ToolTrial.KiotaClient.Models.Rate.CreateFromDiscriminatorValue)?.AsList(); } },
                { "warnings", n => { Warnings = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ToolTrial.KiotaClient.Models.ApiError>("errors", Errors);
            writer.WriteCollectionOfObjectValues<global::ToolTrial.KiotaClient.Models.Rate>("rates", Rates);
            writer.WriteCollectionOfPrimitiveValues<string>("warnings", Warnings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
