// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ToolTrial.KiotaClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The packages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ToolTrial.KiotaClient.Models.Package>? Packages { get; set; }
#nullable restore
#else
        public List<global::ToolTrial.KiotaClient.Models.Package> Packages { get; set; }
#endif
        /// <summary>The serviceCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServiceCode { get; set; }
#nullable restore
#else
        public string ServiceCode { get; set; }
#endif
        /// <summary>The shipFrom property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ToolTrial.KiotaClient.Models.Address? ShipFrom { get; set; }
#nullable restore
#else
        public global::ToolTrial.KiotaClient.Models.Address ShipFrom { get; set; }
#endif
        /// <summary>The shipTo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ToolTrial.KiotaClient.Models.Address? ShipTo { get; set; }
#nullable restore
#else
        public global::ToolTrial.KiotaClient.Models.Address ShipTo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ToolTrial.KiotaClient.Models.RateRequest"/> and sets the default values.
        /// </summary>
        public RateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ToolTrial.KiotaClient.Models.RateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ToolTrial.KiotaClient.Models.RateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ToolTrial.KiotaClient.Models.RateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "packages", n => { Packages = n.GetCollectionOfObjectValues<global::ToolTrial.KiotaClient.Models.Package>(global::ToolTrial.KiotaClient.Models.Package.CreateFromDiscriminatorValue)?.AsList(); } },
                { "serviceCode", n => { ServiceCode = n.GetStringValue(); } },
                { "shipFrom", n => { ShipFrom = n.GetObjectValue<global::ToolTrial.KiotaClient.Models.Address>(global::ToolTrial.KiotaClient.Models.Address.CreateFromDiscriminatorValue); } },
                { "shipTo", n => { ShipTo = n.GetObjectValue<global::ToolTrial.KiotaClient.Models.Address>(global::ToolTrial.KiotaClient.Models.Address.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ToolTrial.KiotaClient.Models.Package>("packages", Packages);
            writer.WriteStringValue("serviceCode", ServiceCode);
            writer.WriteObjectValue<global::ToolTrial.KiotaClient.Models.Address>("shipFrom", ShipFrom);
            writer.WriteObjectValue<global::ToolTrial.KiotaClient.Models.Address>("shipTo", ShipTo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
